### ISSUE TITLE
[기능 개선] 캘린더 목록 체크박스별로 색상 구현하기

### ISSUE THREAD

**Issue by rbdkqk** [codestates/partim3-TIL-client#104]
관련 질문 : https://github.com/codestates/help-desk/issues/2425
   - 참고 링크 : https://medium.com/@colebemis/building-a-checkbox-component-with-react-and-styled-components-8d3aa1d826dd
   - 참고 링크 : https://velog.io/@taewo/%EB%A6%AC%EC%95%A1%ED%8A%B8-Styled-Componets-2%ED%8E%B8

---

아래 코드를 styled components로 구현해야 한다

```css
.checkbox-container input[type='checkbox']:checked + label:before {
  content: '\2713';

  color: white;

  text-shadow: 1px 1px white;

  background: #abb8c3;
  /* 이 값은 캘린더마다 달라야 한다 */

  border-color: #adb8c0;

  box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.05), inset 0px -15px 10px -12px rgba(0, 0, 0, 0.05);
}
```
